name: Publish Gradle package

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: Repository Name
        default: bilal7596/spring-boot-package
        required: true
      branch_name:
        description: Branch Name
        default: main
        required: true
      version_id:
        description: Version
        default: 1.0.0
        required: true

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          repository: ${{ github.event.inputs.repository_name }}
          ref: ${{ github.event.inputs.branch_name }}
          path: workspace

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

#    - name: Set Gradle Version
#      working-directory: workspace
#      run: |
#        echo "version=${{ github.event.inputs.version_id }}" >> gradle.properties

    - name: Build with Gradle
      working-directory: workspace
      run: ./gradlew clean build
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print
      working-directory: workspace/build/libs
      run: |
        pwd

    - name: Print1
      working-directory: workspace/build/libs
      run: |
        ls -la

    - name: Print2
      working-directory: workspace
      run: |
        echo $System.getenv("USERNAME")

    - name: Print3
      working-directory: workspace
      run: |
        echo $System.getenv("TOKEN");

    - name: Publish the Gradle
      working-directory: workspace
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
#    - name: Publish to GitHub Packages
#      run: ./gradlew publish
#      env:
#        USERNAME: ${{ github.actor }}
#        TOKEN: ${{ secrets.GITHUB_TOKEN }}